---
title: "Comparison_GMV"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Comparison_GMV}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE,
                      comment = "#>"
)
```


```{r setup}
library(UniversalShrink)
library(tidyverse)
```


# Generation of the data

```{r}
n = 50
p = 2 * n
mu = rep(0, p)

# Generate Sigma
X0 <- MASS::mvrnorm(n = n, mu = mu, Sigma = diag(p))
H <- eigen(t(X0) %*% X0)$vectors
Sigma = H %*% diag(seq(1, 0.02, length.out = p)) %*% t(H)

# Generate example dataset
X <- MASS::mvrnorm(n = n, mu = mu, Sigma=Sigma)

ones = rep(1, length = p)
V_GMV = 1 / ( t(ones) %*% solve(Sigma) %*% ones)


LossFunction_GMV <- function(weights){
  outOfSampleVariance = t(weights) %*% Sigma %*% weights
  
  Loss_GMV = (outOfSampleVariance - V_GMV) / V_GMV
  
  return (Loss_GMV)
}

OutOfSampleVariance <- function(weights){
  outOfSampleVariance = t(weights) %*% Sigma %*% weights
  
  return (outOfSampleVariance)
}
```

# Computation of the estimators

```{r}
list_GMV = list(
  GMV_MP_shrinkage = GMV_Moore_Penrose_target_eq(Y = t(X), centeredCov = TRUE),
  
  GMV_MP = GMV_Moore_Penrose(Y = t(X), centeredCov = TRUE),
  
  GMV_plugin_MP_shrinked_toIP = GMV_PlugIn(
    Moore_Penrose_shrinkage_toIP(Y = t(X), centeredCov = TRUE)),
  
  GMV_plugin_ridge_target_shrinked_toIP = GMV_PlugIn(
    ridge_target_identity_optimal(Y = t(X), centeredCov = TRUE
                                  )$estimated_precision_matrix),
  
  GMV_plugin_optimal_ridge_shrinkage = GMV_PlugIn(
    ridge_shrinkage_rescaled_optimal(Y = t(X))$estimated_precision_matrix),
  
  GMV_plugin_inv_quadratic_inverse_shrinkage = GMV_PlugIn(
    solve(quadratic_inverse_shrinkage(X = X, centeredCov = TRUE))),
  
  GMV_plugin_higher_order_shrinkage_2 = GMV_PlugIn(
    ridge_higher_order_shrinkage_optimal(Y = t(X), m = 2, centeredCov = TRUE
                                         )$estimated_precision_matrix)
  
  # TODO: add other forms of shrinkage
  # FIXME: see why below does not work
  # ,
  
  # GMV_plugin_higher_order_shrinkage_3 = GMV_PlugIn(
  #   ridge_higher_order_shrinkage_optimal(Y = t(X), m = 3, centeredCov = TRUE
  #                                        )$estimated_precision_matrix),
  
  # GMV_plugin_higher_order_shrinkage_4 = GMV_PlugIn(
  #   ridge_higher_order_shrinkage_optimal(Y = t(X), m = 4, centeredCov = TRUE
  #                                        )$estimated_precision_matrix)
  # ,
  
  # GMV_plugin_higher_order_shrinkage_5 = GMV_PlugIn(
  #   ridge_higher_order_shrinkage_optimal(Y = t(X), m = 5, centeredCov = TRUE
  #                                        )$estimated_precision_matrix),
  
  # GMV_plugin_higher_order_shrinkage_6 = GMV_PlugIn(
  #   ridge_higher_order_shrinkage_optimal(Y = t(X), m = 6, centeredCov = TRUE
  #                                        )$estimated_precision_matrix)
)
```


# Visualization of the loss

```{r}
all_losses = sapply(X = list_GMV, FUN = LossFunction_GMV)
print(all_losses)
```


```{r}
df_all_losses = data.frame(
  loss = unname(all_losses),
  method = names(all_losses)
)


df_all_losses |>
  # filter(method != "GMV_MP") |>
  arrange(desc(loss)) |>
  mutate(method = factor(method, levels = method)) |>
  ggplot() +
  geom_col(aes(x = method, y = loss)) +
  guides(x =  guide_axis(angle = 45))
```

## Focusing on GMV_plugin_higher_order_shrinkage

```{r}
df_all_losses = data.frame(
  loss = unname(all_losses),
  method = names(all_losses)
)


df_all_losses_higher_order = df_all_losses[
  grep("GMV_plugin_higher_order_shrinkage_", x = df_all_losses$method), ] |>
  mutate(m = as.numeric(str_sub(method, start= -1)))


ggplot(df_all_losses_higher_order) +
  geom_col(aes(x = m, y = loss)) +
  scale_y_log10()
```


# Comparison of the out of sample variance

```{r}
all_OutOfSampleVariance = sapply(X = list_GMV, FUN = OutOfSampleVariance)

all_OutOfSampleVariance = c(all_OutOfSampleVariance, V_GMV = V_GMV)

print(all_OutOfSampleVariance)
```


```{r}
df_all_OutOfSampleVariance = data.frame(
  outOfSampleVariance = unname(all_OutOfSampleVariance),
  method = names(all_OutOfSampleVariance)
)


df_all_OutOfSampleVariance |>
  # filter(method != "GMV_MP") |>
  arrange(desc(outOfSampleVariance)) |>
  mutate(method = factor(method, levels = method)) |>
  ggplot() +
  geom_col(aes(x = method, y = outOfSampleVariance)) +
  guides(x =  guide_axis(angle = 45))
```



